import 'classEstablishment.dart';

//OOP list style
List<Establishment> establishmentData = [
  Establishment(
      "assets/images/chowi.png", 
      "Chowi", 
      "Tabunok, Cebu", 
      "Restaurant",
      "Welcome to Uncle Brew",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.6),
  Establishment(
      "assets/images/shomay.png",
      "Shomay",
      "Colon, Cebu",
      "Restaurant",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.8),
  Establishment(
      "assets/images/profile.png",
      "Jolli",
      "Mambaling, Cebu",
      "Hotel",
      "Welcome to Uncle Brew, ",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.1),
  Establishment(
      "assets/images/beach.jpg",
      "Estaka",
      "Compostela, Cebu",
      "Beach",
      "Welcome to Uncle Brew, ",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.2),
  Establishment(
      "assets/images/kuyaJ.jpg",
      "Kuya j",
      "Lilo-an, Cebu",
      "Restaurant",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.9),
  Establishment(
    "assets/images/leona.jpg",
    "Leona",
    "Consolacion, Cebu",
    "Restaurant",
    "Welcome to Uncle Brew, ",
    "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.7),
  Establishment(
      "assets/images/pool.jpg",
      "Pool ni Hugh",
      "Oslob, Cebu",
      "Beach",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.4),
  Establishment(
      "assets/images/tuslob.jpg",
      "Tuslob buwa",
      "Colon, Cebu",
      "Restaurant",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.2),
  Establishment(
      "assets/images/hotel.jpg",
      "Advent guild",
      "Talisay, Cebu",
      "Hotel",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      5.0),
  Establishment(
      "assets/images/piratebeach.jpg",
      "Pirates Cove",
      "Danao, Cebu",
      "Beach",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.4),
  Establishment(
      "assets/images/halohalobeach.jpg",
      "Halo halo",
      "Santander, Cebu",
      "Beach",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.0),
  Establishment(
    "assets/images/donmachis.jpg",
    "Don Machi",
    "Colon, Cebu",
    "Restaurant",
    "Welcome to Uncle Brew,",
    "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.9),
  Establishment(
      "assets/images/fontainehotel.jpg",
      "Fontaine Hotel",
      "Mandaue, Cebu",
      "Hotel",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.7),
  Establishment(
      "assets/images/liyuebar.jpg",
      "Liyue Bar",
      "Basak, Cebu",
      "Restaurant",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.6),
  Establishment(
      "assets/images/sumerubeach.jpg",
      "Sumeru beach",
      "Mambaling, Cebu",
      "Beach",
      "Welcome to Uncle Brew, ",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.5),
  Establishment(
      "assets/images/ethansramen.jpg",
      "Ethans ramen",
      "Inayawan, Cebu",
      "Restaurant",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.1),
  Establishment(
      "assets/images/justinsbeach.png",
      "Justins Backyard",
      "Tungkop, Cebu",
      "Beach",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.2),
  Establishment(
    "assets/images/kurtspalace.jpg",
    "Kurts Palace",
    "Urgello, Cebu",
    "Hotel",
    "Welcome to Uncle Brew,",
    "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
    4.9),
  Establishment(
      "assets/images/rhunsrestau.jpg",
      "Rhuns Eats",
      "Tabunok, Cebu",
      "Restaurant",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.2),
  Establishment(
      "assets/images/kananannijose.jpg",
      "Kan-anan ni Jose",
      "Basak, Cebu",
      "Restaurant",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.3),
  Establishment(
      "assets/images/ninosinn.jpg",
      "Ninos Inn",
      "Naga, Cebu",
      "Hotel",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.6),
  Establishment(
      "assets/images/finasgrill.jpg",
      "Finas grill",
      "Carcar, Cebu",
      "Restaurant",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.1),
  Establishment(
      "assets/images/lemonbeach.jpg",
      "Lemon Beach",
      "Oslob, Cebu",
      "Beach",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.2),
  Establishment(
    "assets/images/carbon.jpg",
    "Carbon Market",
    "Colon, Cebu",
    "Restaurant",
    "Welcome to Uncle Brew,",
    "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
    4.6),
  Establishment(
      "assets/images/tuburanbeach.jpg",
      "Jones Pool",
      "Tuburan, Cebu",
      "Beach",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.4),
  Establishment(
      "assets/images/shangrila.jpg",
      "Shagri-la",
      "Lapu-lapu, Cebu",
      "Hotel",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.1),
  Establishment(
      "assets/images/shakeys.jpg",
      "Shakey's",
      "Mabolo, Cebu",
      "Restaurant",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.2),
  Establishment(
      "assets/images/seol.jpg",
      "Seoul Eatery",
      "Mabolo, Cebu",
      "Restaurant",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.8),
  Establishment(
      "assets/images/ahmes.jpg",
      "Ahmes resort",
      "Lilo-an, Cebu",
      "Beach",
      "Welcome to Uncle Brew,",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      5.0),
  Establishment(
    "assets/images/geralds.jpg",
    "Geralds Lanchaw",
    "Colon, Cebu",
    "Restaurant",
    "Welcome to Uncle Brew,",
    "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
    4.3),
  Establishment(
      "assets/images/kitkats.jpg",
      "Kit Kats",
      "Labangon, Cebu",
      "Hotel",
      "Welcome to Uncle Brew",
      "Lot 5 and 6 Block 20, Samar Loop, Cebu City, 6000 Cebu",
      4.7),
];
